server:
  port: 8080
  servlet:
    context-path: /demo

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  profiles:
    active:
      - ${ACTIVE_SPRING_PROFILE:local}
  application:
    name: eric-cola-demo
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    locations: classpath:/db/migration
    out-of-order: true
    baseline-on-migrate: true
    validate-on-migrate: false
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  config: classpath:${SPRING_CONFIG_FILE:logback-spring.xml}

springdoc:
  swagger-ui:
    path: /portal/api/swagger-ui.html

token:
  secret: sample_key_123456
  expired: 600